from ecom_pipeline.star import FACT_ORDERS_COLUMNS
from ecom_pipeline.warehouse import (
    DIMENSIONS,
    FACT_KEY,
    FACT_TABLE,
    FACT_VALUE_COLUMNS,
    create_fact_load_table_sql,
    create_load_table_sql,
    schema_statements,
    split_statements,
    upsert_dimension_sql,
    upsert_fact_sql,
)


def statement_for(table: str) -> str:
    """The CREATE TABLE statement of ``dw.<table>`` from the packaged schema file."""
    (statement,) = [s for s in schema_statements() if f"TABLE IF NOT EXISTS dw.{table} " in s]
    return statement


def test_split_statements_drops_comments_and_empty_parts():
    script = "-- a comment\nCREATE A (\n  x INT -- inline\n);\n\n-- another\nCREATE B;\n"

    assert split_statements(script) == ["CREATE A (\n  x INT -- inline\n)", "CREATE B"]


def test_schema_file_creates_the_schema_four_tables_and_three_indexes():
    statements = schema_statements()

    assert statements[0] == "CREATE SCHEMA IF NOT EXISTS dw"
    assert sum(s.startswith("CREATE TABLE IF NOT EXISTS") for s in statements) == 4
    assert sum(s.startswith("CREATE INDEX IF NOT EXISTS") for s in statements) == 3
    assert len(statements) == 8


def test_schema_can_be_run_repeatedly():
    # every statement must be guarded, otherwise the second load would fail
    assert all("IF NOT EXISTS" in statement for statement in schema_statements())


def test_dimension_columns_match_the_schema_file():
    for dimension in DIMENSIONS:
        ddl = statement_for(dimension.name)
        for column in dimension.columns:
            assert f" {column} " in ddl, f"{dimension.name}.{column} is missing in the DDL"


def test_fact_columns_match_the_schema_file():
    ddl = statement_for(FACT_TABLE)

    for column in (*FACT_KEY, *FACT_VALUE_COLUMNS):
        assert f" {column} " in ddl, f"{FACT_TABLE}.{column} is missing in the DDL"


def test_fact_load_table_has_all_prepared_fact_columns():
    sql = create_fact_load_table_sql()

    for column in FACT_ORDERS_COLUMNS:
        assert f" {column} " in sql, column


def test_load_table_copies_the_column_types_of_the_dimension_without_rows():
    dimension = next(d for d in DIMENSIONS if d.name == "dim_customers")

    sql = create_load_table_sql(dimension)

    assert "CREATE TEMP TABLE _load_dim_customers ON COMMIT DROP" in sql
    assert sql.endswith("FROM dw.dim_customers WITH NO DATA")
    assert "customer_key" not in sql  # the surrogate key is generated by the database


def test_dimension_upsert_matches_on_the_business_key_and_skips_unchanged_rows():
    dimension = next(d for d in DIMENSIONS if d.name == "dim_customers")

    sql = upsert_dimension_sql(dimension)

    assert "ON CONFLICT (customer_id) DO UPDATE SET" in sql
    assert "city = EXCLUDED.city" in sql
    assert "customer_id = EXCLUDED.customer_id" not in sql  # the key itself is never updated
    assert "IS DISTINCT FROM" in sql
    assert "customer_key" not in sql


def test_fact_upsert_replaces_business_ids_with_surrogate_keys():
    sql = upsert_fact_sql()

    assert "ON CONFLICT (order_id, order_item_id) DO UPDATE SET" in sql
    assert "JOIN dw.dim_customers AS c ON c.customer_id = l.customer_id" in sql
    assert "JOIN dw.dim_products AS p ON p.product_id = l.product_id" in sql
    assert "c.customer_key" in sql
    assert "p.product_key" in sql
    assert "order_id = EXCLUDED.order_id" not in sql
    assert "IS DISTINCT FROM" in sql
